### ISSUE TITLE
Tackle "ValueError: buffer source array is read-only"

### ISSUE THREAD

**Issue by SJTUzhou** [gattia/cycpd#19]
Hi. Thank you for your implementation using Cython.
I am using your code for pointcloud registration where multiple pointclouds should be registered, so I use ray to parallelize my code.
I encountered a small issue but I found the solution here:  [https://github.com/dask/distributed/issues/1978](url)

So I add this function above the definition of class "expectation_maximization_registration";
```
def _memoryview_safe(x):
    """Make array safe to run in a Cython memoryview-based kernel. These
    kernels typically break down with the error ``ValueError: buffer source
    array is read-only`` when running in dask distributed.
    """
    if not x.flags.writeable:
        if not x.flags.owndata:
            x = x.copy(order='C')
        x.setflags(write=True)
    return x
```

and modify the functions "register" and "expectation" in expectation_maximization_registration.py
```
def register(self, callback=lambda **kwargs: None):
    tic = time.time()
    self.transform_point_cloud()
    self.X = _memoryview_safe(self.X)
    self.Y = _memoryview_safe(self.Y)
    self.sigma2 = cy.initialize_sigma2(self.X, self.Y)
    ......
```

```
def expectation(self):
    self.X = _memoryview_safe(self.X)
    self.TY = _memoryview_safe(self.TY)
    self.P1, self.Pt1, self.PX, self.Np, self.E = cy.expectation_2(self.X,
                                                                   self.TY,
                                                                   self.sigma2,
                                                                   self.M,
                                                                   self.N,
                                                                   self.D,
                                                                   self.w)
```

Another small issue is that I have to convert my pointcloud numpy array (np.float64) into array of dtype np.double to avoid the TypeError: No matching signature found when using ray to parallelize the code, but it works well without using ray. I am not sure maybe that's an issue of ray since I am not familiar with Cython.

**Comment by SJTUzhou** [comment]
Since these problems does not occur without using ray, I will just close this issue.

**Comment by gattia** [comment]
@SJTUzhou - Thanks for the interest! Glad that you were able to find a solution. At a minimum, this is a great thing to have here so that others can find this solution if they come across the same problem.
