### ISSUE TITLE
ArrayMemoryError

### ISSUE THREAD

**Issue by han16nah** [gattia/cycpd#48]
I have two point clouds with around 200,000 points each and 3 dimensions. When trying to run `reg = deformable_registration(X = x_ds, Y = y_ds, sigma2=1.5, max_iterations=100, tolerance=1e-5, w=0.1)`, I get the error: "Unable to allocate 1.05 TiB for an array with shape (219795, 219795, 3) and data type float64". I get the same error with [`pycpd`](https://github.com/siavashk/pycpd).

Is there a known limit of points per point cloud that can be processed? Or am I using the package in the "wrong" way?

**Environment:**
 - OS: Windows 11
 - Python: 3.13
 - cycpd: 0.28 (installed from PyPi)

**Comment by gattia** [comment]
If you don't mind posting what you did to solve this that would be great - I'm sure others might find it useful.
